USE [master]
GO
/****** Object:  Database [PruebaTecnicaDB2]    Script Date: 29/10/2022 6:42:08 p. m. ******/
CREATE DATABASE [PruebaTecnicaDB2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaTecnicaDB2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaTecnicaDB2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaTecnicaDB2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaTecnicaDB2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PruebaTecnicaDB2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaTecnicaDB2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaTecnicaDB2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaTecnicaDB2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaTecnicaDB2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PruebaTecnicaDB2] SET QUERY_STORE = OFF
GO
USE [PruebaTecnicaDB2]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 29/10/2022 6:42:08 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[CodigoProducto] [int] IDENTITY(1,1) NOT NULL,
	[DescripcionProducto] [varchar](100) NOT NULL,
	[EstadoProducto] [varchar](50) NOT NULL,
	[FechaFabricacion] [date] NULL,
	[FechaValidez] [date] NULL,
	[CodigoProveedorID] [int] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[CodigoProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Proveedor]    Script Date: 29/10/2022 6:42:08 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Proveedor](
	[CodigoProveedor] [int] IDENTITY(1,1) NOT NULL,
	[DescripcionProveedor] [varchar](100) NOT NULL,
	[TelefonoProveedor] [bigint] NULL,
 CONSTRAINT [PK_Proveedor] PRIMARY KEY CLUSTERED 
(
	[CodigoProveedor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD  CONSTRAINT [FK_Producto_Proveedor] FOREIGN KEY([CodigoProveedorID])
REFERENCES [dbo].[Proveedor] ([CodigoProveedor])
GO
ALTER TABLE [dbo].[Producto] CHECK CONSTRAINT [FK_Producto_Proveedor]
GO
USE [master]
GO
ALTER DATABASE [PruebaTecnicaDB2] SET  READ_WRITE 
GO
